baseURL = "http://localhost:1313/"
languageCode = "en"
#theme = "adritian-free-hugo-theme" <- using modules, do not need this line
custom_css = "assets/css/custom.css"

# https://gohugo.io/content-management/taxonomies/
disableKinds = ["taxonomy", "term", "rss"]
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/zetxek/adritian-free-hugo-theme"

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[params]

  # Open Graph
  images = ['/android-chrome-512x512.png']

  sections = ["showcase", "client-and-work", "education", "contact"]

  homepageExperienceCount = 3

  [params.analytics]
  ## Analytics parameters.
  ### Supported so far: Vercel (Page Insights, Analytics)
  ### And Google (Tag Manager, Analytics)

  # controls vercel page insights - disabled by default
  # to enable, just set to true
  vercelPageInsights = false
  vercelAnalytics = false

  # google analytics and tag manager. to enable, set "enabled" to true
  # and add the tracking code (UA-something for analytics, GTM-something for tag manager)
  [params.analytics.googleAnalytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.analytics.googleTagManager]
      code = "GTM-XXXXX"
      enabled = false

[build]
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true

[params.languages.selector.disable]
  footer = false

[languages]
  [languages.en]
  disabled = false
  languageCode = 'en'
  languageDirection = 'ltr'
  languageName = 'English'
  title = 'Echo Nattinger'
  weight = 0

  [languages.en.menus]
  [[languages.en.menus.header]]
  name = 'Projects'
  URL = '#portfolio'
  weight = 2
  [[languages.en.menus.header]]
  name = 'Education'
  URL = '#education'
  weight = 3
  [[languages.en.menus.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6


  [[languages.en.menus.footer]]
  name = "Projects"
  URL = "#portfolio"
  weight = 2
  [[languages.en.menus.footer]]
  name = "Education"
  URL = "#education"
  weight = 3
  [[languages.en.menus.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4

# Experience
[params.experience]
  showJobCard = true  # Set to false for hide the job card

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "assets/css/custom.css"
  [[params.plugins.css]]
  URL = "css/adritian-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

  # SCSS Plugins
  [[params.plugins.scss]]
  URL = "scss/adritian.scss"


# theme/color style
[params.colorTheme]
color='bs-teal'

## the following configuration would disable automatic theme selection
[params.colorTheme.auto]
disable = true

## the following parameter will disable theme override in the footer
[params.colorTheme.selector.disable]
footer = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

## by default we allow override AND automatic selection
